# Numpy & Pandas

## Numpy

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

# Khác list:
# - list chứa mọi thứ
# - array chỉ chứa 1 kiểu dữ liệu

[1 2 3]


In [2]:
# Array có thể là 1D, 2D, 3D, ... nD

b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# Các thao tác quan trọng
# 1. tạo nhanh
print(np.zeros((2,3)))   # toàn số 0
print(np.ones((2,3)))    # toàn số 1
print(np.arange(0,10))   # giống range

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 2. Tính toán
a = np.array([1,2,3])
print(a + 10)     # [11,12,13]
print(a * 2)      # [2,4,6]
# list không làm được điều này

# 3. Truy cập phần tử
print(a[0])       # 1

# 4. thống kê nhanh 
print(np.mean(a))  # .mean() là hàm tính trung bình
print(np.max(a))   # .max() là hàm tính max
print(np.min(a))   # .min() là hàm tính min
print(np.sum(a))   # .sum() là hàm tính tổng

[11 12 13]
[2 4 6]
1
2.0
3
1
6


## Pandas

**Dùng để xử lý dữ liệu dạng bảng (giống Excel)**

In [2]:
import pandas as pd

data = {
    "name": ["An", "Bình", "Cường"],
    "age": [20, 21, 22]
}

df = pd.DataFrame(data)
print(df)

ModuleNotFoundError: No module named 'pandas'