# eigenvalues / eigenvectors

Khi bạn có ma trận A tác động lên một vector x:

- Thông thường: vector sẽ đổi hướng + đổi độ dài
- Nhưng có một số vector đặc biệt:
    - KHÔNG đổi hướng
    - Chỉ bị co lại hoặc kéo dài

👉 Những vector đặc biệt đó gọi là eigenvectors
👉 Mức độ co/giãn gọi là eigenvalues

Công thức: Ax=λx

- A: ma trận
- x: eigenvector
- λ: eigenvalue

👉 Nghĩa là: Nhân ma trận A với x chỉ làm x scale lên λ lần, không đổi hướng

In [2]:
# tính eigenvalues/eigenvectors
import numpy as np

A = np.array([
    [2, 0],
    [0, 3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

# Hàm np.linalg.eig() trả về một tuple gồm hai phần: eigenvalues và eigenvectors.

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

""" Lưu ý quan trọng
Trong NumPy, eigenvectors nằm theo cột, không phải theo hàng. 
eigenvectors =
[[1. 0.]
 [0. 1.]]
Nghĩa là:
- Eigenvector thứ nhất là cột 1: [1. 0.] ứng với eigenvalue 2
- Eigenvector thứ hai là cột 2: [0. 1.] ứng với eigenvalue 3
"""

Eigenvalues:
[2. 3.]
Eigenvectors:
[[1. 0.]
 [0. 1.]]


' Lưu ý quan trọng\nTrong NumPy, eigenvectors nằm theo cột, không phải theo hàng. \neigenvectors =\n[[1. 0.]\n [0. 1.]]\nNghĩa là:\n- Eigenvector thứ nhất là cột 1: [1. 0.] ứng với eigenvalue 2\n- Eigenvector thứ hai là cột 2: [0. 1.] ứng với eigenvalue 3\n'

In [3]:
# In ra cho dễ hiểu hơn
A = np.array([
    [2, 0],
    [0, 3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

for i in range(len(eigenvalues)):
    print("Eigenvalue:", eigenvalues[i])
    print("Eigenvector:", eigenvectors[:, i])
    print()

Eigenvalue: 2.0
Eigenvector: [1. 0.]

Eigenvalue: 3.0
Eigenvector: [0. 1.]



In [5]:
# Kiểm tra lại công thức Ax=λx
for i in range(len(eigenvalues)):
    lambda_i = eigenvalues[i]
    x = eigenvectors[:, i]

    left = A @ x
    right = lambda_i * x

    print("A @ x =", left)
    print("lambda * x =", right)
    print("Có bằng nhau không?", np.allclose(left, right))
    print()
    
"""
np.allclose(left, right)
kiểm tra hai kết quả có gần bằng nhau không.
Dùng allclose thay vì == vì máy tính có thể có sai số rất nhỏ khi tính số thực.
"""

A @ x = [2. 0.]
lambda * x = [2. 0.]
Có bằng nhau không? True

A @ x = [0. 3.]
lambda * x = [0. 3.]
Có bằng nhau không? True



'\nnp.allclose(left, right)\nkiểm tra hai kết quả có gần bằng nhau không.\nDùng allclose thay vì == vì máy tính có thể có sai số rất nhỏ khi tính số thực.\n'

In [6]:
# Code đầy đủ
import numpy as np

A = np.array([
    [2, 0],
    [0, 3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Ma trận A:")
print(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

print("\nKiểm tra Ax = lambda x:")

for i in range(len(eigenvalues)):
    lambda_i = eigenvalues[i]
    x = eigenvectors[:, i]

    left = A @ x
    right = lambda_i * x

    print(f"\nEigenvalue {i+1}: {lambda_i}")
    print("Eigenvector:", x)
    print("A @ x:", left)
    print("lambda * x:", right)
    print("Đúng không?", np.allclose(left, right))

Ma trận A:
[[2 0]
 [0 3]]

Eigenvalues:
[2. 3.]

Eigenvectors:
[[1. 0.]
 [0. 1.]]

Kiểm tra Ax = lambda x:

Eigenvalue 1: 2.0
Eigenvector: [1. 0.]
A @ x: [2. 0.]
lambda * x: [2. 0.]
Đúng không? True

Eigenvalue 2: 3.0
Eigenvector: [0. 1.]
A @ x: [0. 3.]
lambda * x: [0. 3.]
Đúng không? True


### Bài tập

In [ ]:
# Bài 1.
A = np.array([
    [4, 0],
    [0, 5]
])

#Yêu cầu:
#Tính eigenvalues và eigenvectors
#Kiểm tra lại Ax=λx

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

# Giải thích:
# Trục x → scale 4 lần
# Trục y → scale 5 lần

[4. 5.]
[[1. 0.]
 [0. 1.]]


In [ ]:
# Bài 2.
B = np.array([
    [2, 1],
    [1, 2]
])

eigenvalues, eigenvectors = np.linalg.eig(B)

for i in range(len(eigenvalues)):
    print("Eigenvalue:", eigenvalues[i])
    print("Eigenvector:", eigenvectors[:, i])
    print()
    
# Hiểu bản chất
# Ma trận này không còn kéo theo trục x/y nữa
# → nó kéo theo hướng chéo
# 👉 Đây là lúc eigenvector bắt đầu “có ý nghĩa thật sự”

Eigenvalue: 3.0
Eigenvector: [0.70710678 0.70710678]

Eigenvalue: 1.0
Eigenvector: [-0.70710678  0.70710678]



In [11]:
# Bài 3.

C = np.array([
    [3, 1, 0],
    [1, 3, 0],
    [0, 0, 2]
])

eigenvalues, eigenvectors = np.linalg.eig(C)

for i in range(len(eigenvalues)):
    print("Eigenvalue:", eigenvalues[i])
    print("Eigenvector:", eigenvectors[:, i])
    print()

Eigenvalue: 4.0
Eigenvector: [0.70710678 0.70710678 0.        ]

Eigenvalue: 2.0
Eigenvector: [-0.70710678  0.70710678  0.        ]

Eigenvalue: 2.0
Eigenvector: [0. 0. 1.]

